spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: mySecretKeyForJWTTokenGeneration12345678901234567890
  expiration: 86400000 # 24 hours in milliseconds